### ISSUE TITLE
Use a new Github API key for pushing docs

### ISSUE THREAD

**Issue by jgilchrist** [tomassedovic/tcod-rs#102]
Currently, as I set up the automatic pushing of the documentation, Github sees me as having pushed to this repository whenever the documentation is updated (that is, whenever something is committed to master) - see [this](https://github.com/jgilchrist?tab=activity).

@tomassedovic is it possible we could switch to use an API key under your account? This will also prevent any breakage if for whatever reason I don't have contributor rights to this repository in future.

**Comment by jgilchrist** [comment]
This doesn't appear to have worked. If you look at the expanded output at the bottom of the most recent build there's an error:

```
Collecting ghp-import
  Downloading ghp-import-0.4.1.tar.gz
Installing collected packages: ghp-import
  Running setup.py install for ghp-import
    changing mode of build/scripts-2.7/ghp-import from 644 to 755
    changing mode of /usr/local/bin/ghp-import to 755
Successfully installed ghp-import-0.4.1
remote: Anonymous access to tomassedovic/tcod-rs.git denied.
fatal: Authentication failed for 'https://@github.com/tomassedovic/tcod-rs.git/'
Done. Your build exited with 0.
```

**Comment by tomassedovic** [comment]
Sigh. Maybe I gave it bad permissions. I'll try again a bit later.

**Comment by tomassedovic** [comment]
Okay, it seems to be working now. I encrypted a wrong environment variable. It shows on my activity, the branch was updated and travis log no longer shows the error.

Closing again, feel free to reopen if it's still not all right.

**Comment by jgilchrist** [comment]
Nope, it's all good. Thanks a lot!
