### ISSUE TITLE
Duplicating tcod header files

### ISSUE THREAD

**Issue by jgilchrist** [tomassedovic/tcod-rs#114]
What is the reasoning behind having two copies of the libtcod header files in the repository? One is located at `include/` and one is in `tcod-sys/libtcod/include/`. Is one of these redundant, or do we need both?

**Comment by tomassedovic** [comment]
`include/` was the input to rust-bindgen to generate the bindings that are now in tcod-sys (before Cargo even existed iirc). We can just delete it now.
