### ISSUE TITLE
Windows builds

### ISSUE THREAD

**Issue by Gustorn** [tomassedovic/tcod-rs#141]
This question is to anyone, who managed to build this on Windows previously: what setup did you use? Does it still work? The MinGW distro advertised on the main project page was broken by the addition of the `time` crate dependency I think. Even when removing the references to `time` it still doesn't want to compile for me. I tried with:

1. The original MinGW + MSYS
2. MSYS2 with mingw-w64-x86_64/i686 with rebuilt SDL dependencies.
3. TDM-GCC 32/64 bit toolchain.

All of these failed at some point of the compilation (I had all the dependencies).

`Rust` used: the beta, downloaded today from the official site (tried both i686 and x86_64).
`gcc`: various, from 4.8.2 - 4.9.1 I think

Sorry for no concrete error messages, but I'm writing this on the go. I'll post some results when I get home.

**Comment by dkaste** [comment]
I was able to get it to compile on windows today, but I couldn't get it to link with the built `libtcod.dll`.

My setup was:
* 64-bit Windows 7
* 32-bit Rust compiler (`rustc 1.0.0-beta (9854143cb 2015-04-02) (built 2015-04-02)`)
* MSYS2 (using the "MinGW-w64 Win32 Shell" shortcut, and as a result 32-bit `gcc`)

For some reason `ld` keeps skipping `libtcod.dll` as if it has incompatible architecture, and I'm not sure how that would be possible.

**Comment by Gustorn** [comment]
This is really interesting, today `cargo build` worked for me out of the box, but all the examples crash on launch.

**Comment by Gustorn** [comment]
Never mind, I forgot to copy the libtcod DLLs after I reinstalled my VM, it actually works fine now. I have no idea why I was having so much trouble the last time. I even used the same version of everything.

**Comment by dkaste** [comment]
May I ask what you ended up using? I'm currently stuck on getting the `time` crate to build. It keeps failing to build because "64-bit mode not compiled in" despite ensuring that all my compilers are 32-bit.

**Comment by dkaste** [comment]
Oh, the (new?) Rust installer installs x86 and x64 versions separately. Removing the 64-bit one and updating my `PATH` fixed my problems.

**Comment by Gustorn** [comment]
I still don't know what originally caused my problems (I suspect that I had mixed `i686` and `x86_64` libraries / compilers as well. Still it might be worth mentioning on the main page, that this will only work on 32-bit toolchains.

**Comment by Gustorn** [comment]
As far as I'm concerned this is resolved. Could we close it?

**Comment by tomassedovic** [comment]
Since both of you got it running, I'll close this -- we can reopen later if necessary.

It'll probably be a while before I do another round of Windows testing, but I'm happy to add fixes to the docs if you have specific suggestions.
