### ISSUE TITLE
Blit macro

### ISSUE THREAD

**Issue by Gustorn** [tomassedovic/tcod-rs#148]
I though about how we could make the usage of `blit` a little more user friendly. There are two distinct ways: we could declare more types (`Point`, `Region`, etc.) or use macros. The types have the drawback of only being used in this one place, and we would be exporting them into the public API. If we introduced macros the crate would have to be imported with `#[macro_use]` (if you wanted to use the macros, of course). I prefer the macro solution, so I came up with the following macro:

```rust
macro_rules! blit_console {
    (Src($source: expr, TopLeft($sx: expr, $sy: expr), Size($width: expr, $height: expr)),
     Dst($dest: expr, TopLeft($dx: expr, $dy: expr)),
     Alpha { fg: $fg: expr, bg: $bg: expr }) => (
        blit($source, $sx, $sy, $width, $height, $dest, $dx, $dy, $fg, $bg);
    );
}
```

This makes the following example: 

```rust
console::blit(&direct, 0, 0, 20, 20, &mut root, 0, 0, 1.0, 1.0);
```

Into this:
```rust
blit_console!(Src(&direct, TopLeft(0, 0), Size(20, 20)),
              Dst(&root, TopLeft(0, 0)),
              Alpha { fg: 1.0, bg: 1.0 });
```

Now this obviously tries to emulate custom types, but it's a fairly nice API to use nonetheless. Should we do something like this? If yes, any suggestions on changing/improving the macro?

**Comment by tomassedovic** [comment]
Yeah, I don't think defining types that are only used in one place makes that much sense. Regarding the API of `console::blit`, I think we could at least group the related values into tuples (like we do in path finding):

    console::blit(&direct, (0, 0), (20, 20), &mut root, (0, 0), 1.0, 1.0);

I'm not against adding a macro, but this doesn't seem like it's going to be used in a game so much to justify the effort. Like, people are probably going to call blit in one or two places, tops. But if you want, yeah, we can add it.

**Comment by Gustorn** [comment]
I'm not that insistent on adding the macro, and you're right, it's probably only going to be called a few times in the rendering code. The tuple change sounds nice, I'll send a PR for that later.
