### ISSUE TITLE
Operators for wrapper types

### ISSUE THREAD

**Issue by Gustorn** [tomassedovic/tcod-rs#172]
I started working on the heightmap wrapper and noticed that a large portion of the operations are basic arithmetic functions. In the current library `Color` has all its operations defined via member functions. We could move a lot of them out into `std::ops` implementations and free functions. Is this something we should do? If yes, should we still keep the explicit functions?

**Comment by tomassedovic** [comment]
I'm fine implementing the ops traits where it makes sense. Does it for colours, though? I don't know enough about colour theory (or the practice in computer graphics) to know if these are the standard operations of if they're libtcod-specific (I know about `lerp` but that doesn't have a suitable operator anyway).

Not sure about converting methods to free functions, though. I'm not opposed to it per se, but the methods seem a bit more convenient to me.

But yeah, if we do implement some of the ops traits, I think we can remove the corresponding methods.

**Comment by Gustorn** [comment]
I don't mean converting all methods to free functions, just when it makes sense. Take `lerp` for example: you are essentially interpolating between two colors, where neither are "more important" than the other. In this case `lerp(from, to, t)` makes more sense to me than `from.lerp(to, t)`. But when an operation is clearly performed on the struct itself then methods are fine: `color.shift_hue(val)` or `color.hsv()` for example.

As for the `Color` operators: +, -, *, / are widely accepted operators when working with colors. A few notable examples: [Unity](http://docs.unity3d.com/ScriptReference/Color.html), [UnrealEngine](http://wiki.beyondunreal.com/Color), all shader languages (even though colors are usually defined as   `vec4`s)
