### ISSUE TITLE
wait_for_keypress as static?

### ISSUE THREAD

**Issue by GGalizzi** [tomassedovic/tcod-rs#176]
So, I'm no expert so this is just a question rather than a suggestion.

It has been a while since I touched my roguelike, and noticed there was a big rewrite on how Console works in tcod-rs.

The question is: Why can't `wait_for_keypress` be a static method of Root? Similar as before, since the function never uses `self`.

Passing around root can be very inconvenient sometimes (and needs a considerable rewrite of functions in my game).

I made it static in my fork and it works fine, so what are the reasons for the way it is now?

**Comment by Gustorn** [comment]
The problem with function on `Root` being static is that they aren't safe: some methods in `libtcod` are defined as:

1. Only callable before `root_init`
2. Only callable after `root_init`

Apart from that, it's trivial to cause segfaults with the static methods in a multithreaded context (in safe Rust). This should be avoided when possible, and having a `&self` paramenter basicly makes the borrow checker available for us.

We could pepper the code with `lazy_static!` mutexes for mutual exclusion on operations that warrant it, but it wouldn't be very Rustic...

**Comment by GGalizzi** [comment]
I see, thank you for the answer, I took a look at the issue you linked and now I understand and agree with the change.
