### ISSUE TITLE
[Question] Root instance methods instead of static?

### ISSUE THREAD

**Issue by tomob** [tomassedovic/tcod-rs#183]
Consider method like this:

```rust
    /// Returns true if the `Root` console is currently active.
    pub fn is_active(&self) -> bool {
        unsafe {
            ffi::TCOD_console_is_active() != 0
        }
    }
```
Why this function takes `&self`? It would make equally much sense for it to take no parameters and be invoked as `Root::is_active()`. What is the reason to drag a pointer to root instance around? 

There a number of function that never use `self` in `Root`, and the question concerns them as well.

**Comment by Gustorn** [comment]
#176 #137

**Comment by tomob** [comment]
Heh, I'm not the only one. The explanation is fair enough.

Thank you.
