### ISSUE TITLE
Creating and destroying Namegen causes segfault

### ISSUE THREAD

**Issue by tomob** [tomassedovic/tcod-rs#189]
Consider the following code:

```rust
extern crate tcod;
use tcod::namegen::Namegen;

fn main() {
    let namegen = Namegen::new();
}
```

Running it causes a segfault. It can be trivially fixed with a patch namegen_c.c in the tcod_sys (see https://dl.dropboxusercontent.com/u/311875/namegen_c.c.patch) but:

1. I'm very hesitant to do any monkey-patching in external (not owned) code, and
2. It is not a libtcod bug; if I understand correctly, the only way to start using Namegen in C is to call it's `parse` function.

Maybe `Namegen` should have a flag set when `parse`(`_with_rng`) is called and call `TCOD_name_destroy` only when this flag is set?

**Comment by tomassedovic** [comment]
Ouch! How about not calling `TCOD_name_destroy` when `rng` is empty?

Otherwise I agree on both counts. We've done 1) already but with the expectation that the same patch will get accepted upstream because it fixed a real issue.

**Comment by tomob** [comment]
Thumbs up!
