### ISSUE TITLE
Mac OSX build issues with SDL header path

### ISSUE THREAD

**Issue by agentgt** [tomassedovic/tcod-rs#203]
When I build on Mac OSX with homebrew and SDL installed I get:

```
STDERR: In file included from src/bresenham_c.c:28:
include/libtcod.h:109:10: fatal error: 'SDL/SDL.h' file not found
#include "SDL/SDL.h"
```

`sdl-config --cflags` reports this: 
`-I/usr/local/include/SDL -D_GNU_SOURCE=1 -D_THREAD_SAFE`

So I manually changed the `libtcod/makefiles/makefile-osx` in the libtcod directory to have its CFLAGS include `-I/usr/local/include` which seems precarious but apparently compiles fine. 

This is probably a libtcod bug or my configuration but in case others have this issue I thought I might as well report it.

**Comment by Gustorn** [comment]
This is really strange, since it should already include the value returned from `sdl-config` (it's rtight there in the makefile0.

Does the same thing happen if you just run make manually with the makefile (without your modification)?

Could you post the output of: 

```shell
cd <tcod-rs dir>/tcod_sys/libtcod
make -f makefiles/makefile-osx -B
```

**Comment by agentgt** [comment]
Yes the same thing happens. And I was initially doing the manual build to get it to work. To be honest I think its the include itself. I am surprised its `#include "SDL/SDL.h"` and not just `#include "SDL.h"`.

**Comment by Gustorn** [comment]
Oh, I see the problem. `/usr/local/include` is not in your standard include paths (your C compiler doesn't try to search it by default). I don't think we should change the makefiles: having SDL installed somewhere your compiler can find is a reasonable requirement in my opinion. 

Could you try running:

```
xcode-select install
```

And then retry with the unmodified makefile?

**Comment by agentgt** [comment]
Yep that was it. This is a new machine and I thought I had already done that.

**Comment by JoeCostanzo** [comment]
+1, helped with my problem.

**Comment by whgns** [comment]
This did nothing for my issue. 

xcode-select returns:
 `xcode-select: error: command line tools are already installed, use "Software Update" to install updates`

**Comment by ArjunNair** [comment]
> This did nothing for my issue, which is the same as the original poster and follows similar symptoms of the other posters.
> 
> xcode-select returns:
> `xcode-select: error: command line tools are already installed, use "Software Update" to install updates`

What worked finally for me was to reinstall sdl2 ("brew reinstall sdl2" in my case) and use <SDL2/SDL.h> and similarly for other SDL related includes. Note it's SDL**2** because that's what I am using.
