### ISSUE TITLE
Fix the failures on Crater

### ISSUE THREAD

**Issue by tomassedovic** [tomassedovic/tcod-rs#210]
Crater is a tool that compiles everything on http://crates.io with two version of the Rust compiler to detect breakage.

Tcod is failing, because the build script in tcod-sys is expecting SDL stuff that's not present in the build environment:

https://tools.taskcluster.net/task-inspector/#oHQxc8A-REGyGXfzk37EPQ/
https://tools.taskcluster.net/task-inspector/#KXt0JaJ9QXWWBJsMyttAFg/

See the last few comments on #205 for some discussion around this. Since we only care about the Rust code for Crater runs, we can use its environment variables to detect that and not do anything in build.rs.

**Comment by Gustorn** [comment]
I was under the impression that SDL is a hard dependency for libtcod (at least the makefiles don't seem to indicate otherwise). I might be misunderstanding how `cargo build` works, but doesn't `tcod-rs` need `tcod_sys` which in turn depends on SDL to be present?

**Comment by tomassedovic** [comment]
Yes if you actually want to use it. But I think you can still compile the rust code without it.

But I'm thinking, we don't build libtcod at all, basically making build.rs a no-op. So when you actually try to run any of the samples or whatever, you'd get a linker failure. But tcod and tcod-sys should still compile I think -- which is all we care about with crater.

**Comment by Gustorn** [comment]
You're right. For some reason I thought `tcod_sys` would fail, but I guess I was wrong.

**Comment by tomassedovic** [comment]
Well we still need to verify this, I'm just guessing here. But I think it should work.

**Comment by Gustorn** [comment]
I just tried it with `build.rs` completely commented out. `build` works just fine, `test` or `run --example` fails with linker errors, just as you said.

**Comment by tomassedovic** [comment]
\o/
