### ISSUE TITLE
Streamline building using the gcc crate

### ISSUE THREAD

**Issue by LaylConway** [tomassedovic/tcod-rs#212]
Currently tcod-sys builds using make while trying to detect the system it's on. It makes mistakes with newer versions of MSYS2 and MSVC versions of rustc. Replacing the makefile system with a system that makes use of the [gcc crate](https://crates.io/crates/gcc) will streamline compiling and will allow it to automatically use the VC++ compiler if needed.

**Comment by tomassedovic** [comment]
I haven't looked at the gcc crate much yet, but yeah, looks like it'd work. On the other hand, the makefiles aren't really trivial so I'm not too hot on reimplementing them.

I wonder whether fixing the detection code (to differentiate between the mingw and msvc targets) might be safer.

**Comment by LaylConway** [comment]
On a MSVC platform, it's unlikely make is installed at all in the first place. A good middle-ground for now would be to actually fix the mingw make file for the newer versions of MSYS2 (which is now the recommended way to install mingw).

**Comment by tomassedovic** [comment]
Of course, that makes sense. Back when I tried it on Windows, MSVC wasn't supported yet but we definitely want to provide it. So yeah, +1 to that idea.

Can you be more specific about the MSYS2 fixes? I'm not terribly familiar Windows dev unfortunately :-(.

**Comment by LaylConway** [comment]
It's a simple difference, in MSYS2 if you install gcc, the command isn't prefixed anymore by "mingw32-".

**Comment by tomassedovic** [comment]
The #214 pull request closes this issue. Thanks & sorry for the time it took me to do this.
