### ISSUE TITLE
Cargo.toml's libc can cause compilation errors

### ISSUE THREAD

**Issue by bastienleonard** [tomassedovic/tcod-rs#216]
The required version is 0.1, so I was running into this error: https://github.com/rust-lang-deprecated/time/issues/84

Removing Cargo.lock fixed the problem.
It seems like a tilde or caret requirement would work more reliably, but I didn't create a pull merge because I have no experience with handling this.

**Comment by tomassedovic** [comment]
Thanks!

I set up a repro case for this, but no matter what I put in `Cargo.toml` (including things like `^0.2.8`, `=0.2.8` etc.) it still tried (and failed) to build libc 0.1.0 if it was in `Cargo.lock` already.

So: I will submit a pull request changing libc dependency to "^0.1.12" to signal the intent, but that would not help in your case unfortunately :-(. That looks like a Cargo bug to me to be honest: if the dependencies explicitly change, Cargo.lock should be updated imho.

**Comment by bastienleonard** [comment]
Thanks!
