### ISSUE TITLE
OS X Building Error

### ISSUE THREAD

**Issue by jmc-figueira** [tomassedovic/tcod-rs#232]
I followed the building instructions, and after obtaining an SDL include error, I followed the instructions from Issue #203 to fix it. But now, another error has popped up, and I am not sure what is causing it:

```
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"sdl\"`: No such file or directory (os error 2)"', ../src/libcore/result.rs:837
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Do you have any idea what might be causing this issue?

**Comment by tomassedovic** [comment]
Looks like you might not have `pkg-config` installed.

Try running `pkg-config` on its own in your terminal. If it isn't there, you should be able to install it with [Homebrew](https://brew.sh/):

    brew install pkg-config

After that (or if you already have it) try to run this directly:

    pkg-config --libs --cflags sdl

It should succeed and print out something like this:

    -D_GNU_SOURCE=1 -D_REENTRANT -I/usr/include/SDL -lSDL -lpthread

(I'm on Linux now so your output will not be exactly the same)

If that fails, can you make sure you have SDL installed?

    brew install sdl

**Comment by jmc-figueira** [comment]
Thank you for the assistance, it was pkg-config that was missing.

**Comment by tomassedovic** [comment]
Sorry for the complication. I don't own a Mac so I hadn't realised pkg-config isn't installed by default until you hit it. I've created a pull request that adds it to the readme.
