### ISSUE TITLE
How to run examples?

### ISSUE THREAD

**Issue by honza** [tomassedovic/tcod-rs#238]
Everything seems to compile fine but I can't seem to run the examples properly.

```
~/roguelike-tutorial on master  $ cargo build --release
   Compiling lazy_static v0.1.14
   Compiling bitflags v0.1.1
   Compiling winapi-build v0.1.1
   Compiling pkg-config v0.3.7
   Compiling libc v0.2.12
   Compiling gcc v0.3.25
   Compiling libc v0.1.8
   Compiling rustc-serialize v0.3.18
   Compiling winapi v0.2.1
   Compiling advapi32-sys v0.1.2
   Compiling rand v0.3.11
   Compiling tcod-sys v4.0.1
   Compiling tcod v0.10.0
   Compiling roguelike-tutorial v0.1.0 (file:///home/[...]/roguelike-tutorial)
warning: function is never used: `create_v_tunnel`, #[warn(dead_code)] on by default
   --> src/bin/part-3a-building-blocks.rs:111:1
    |
111 |   fn create_v_tunnel(y1: i32, y2: i32, x: i32, map: &mut Map) {
    |  _^ starting here...
112 | |     // vertical tunnel
113 | |     for y in cmp::min(y1, y2)..(cmp::max(y1, y2) + 1) {
114 | |         map[x as usize][y as usize] = Tile::empty();
115 | |     }
116 | | }
    | |_^ ...ending here

    Finished release [optimized] target(s) in 31.73 secs
~/roguelike-tutorial on master  $ ./target/release/part-13-adventure-gear 
./target/release/part-13-adventure-gear: error while loading shared libraries: libtcod.so: cannot open shared object file: No such file or directory
```

This is with latest stable Rust, 1.15.1

How can I run the examples so that the executable can find the `.so` file?

**Comment by tomassedovic** [comment]
If it's an example (i.e. in the examples directory), run: `cargo run --example name`.

So in the tcod-rs checkout you can do:

    cargo run --example keyboard

If it's under the `src/bin` directory (e.g. in the roguelike-tutorial repo you're using), use the `--bin` option instead:

    cargo run --bin part-13-adventure-gear

In either case, you can set the `LD_LIBRARY_PATH` to point to the directory containing `libtcod.so` (which is usually `target/{debug,release}/tcod-sys-$HASH/out/`). You can pass `--release` to `cargo run` to get the optimised version. 

This is all rather unfortunate, but unless I compile the underlying libtcod library statically (which seems super complicated), there's not much we can do here.

This is documented in the tcod-rs README (albeit further down the line) and I thought I've described it in the roguelike tutorial, too but apparently not (created an issue now).

**Comment by honza** [comment]
Ah, I see. Yes, I saw the documentation but my problem was the cargo command, I think. Thanks for explaining this --- and for your patience despite my clearly reporting this on the wrong repository :(

Works great!

**Comment by tomassedovic** [comment]
haha no worries
