### ISSUE TITLE
Drawing ASCII codes which have been mapped to tiles in font crashes, drawing text from same tiled font is offset

### ISSUE THREAD

**Issue by christopherdumas** [tomassedovic/tcod-rs#247]
I have a project, [here](github.com/christopherdumas/Skyspace). I'm attempting to use a tileset, using the `tcod_sys` functions to map ASCII codes to the locations of the tiles. However, my program crashes as soon as I try to draw these tiles to the screen. If I disable the tiles (but still use the font where they are placed) then all text bitmaps are shifted down by roughly two and a third lines. Here is how to navigate my project: in assets, the `master16x16_ro.png` has the tileset/font, and my tile loading logic is in `src/main.rs` at the top of the file. I tried using OpenGL, GLSL, and SDL, and all three crash on my attempt to use the tiles that I mapped. You can see my mapping code in `worldgen/terrain.rs` near the top of the file (after the imports).

Here is a picture of my program running **without** tiles enabled:
![screen shot 2017-07-11 at 1 40 52 pm](https://user-images.githubusercontent.com/1920151/28090250-8df07946-6640-11e7-9e2e-7fe79d460ee8.png)
As you can see in that image, not only are characters wrong, but they are taking small clips of others below them. For instance, the brown chars were supposed to be the second block, instead they are the line intersection two rows below, with a bit of the ß below taken off. For your convenience, here is my tileset:

![master16x16_ro](https://user-images.githubusercontent.com/1920151/28090307-bf23a326-6640-11e7-8a76-c4f3c7839c3c.png)

The tileset on roguecentral is missing so my organization of the tileset is complete conjecture. I would appreciate any kind of help I can get!

**Comment by christopherdumas** [comment]
I mentioned this in issue #244.

**Comment by tomassedovic** [comment]
Based on conversation in #244, I'm closing this. Feel free to reopen it or create a new issue if think it's necessary.
