### ISSUE TITLE
gcc-rs v0.3.53 appears to have changed their API

### ISSUE THREAD

**Issue by huhlig** [tomassedovic/tcod-rs#251]
warning: use of deprecated item: gcc::Config has been renamed to gcc::Build
  --> tcod_sys\build.rs:10:22
   |
10 |     let mut config = gcc::Config::new();
   |                      ^^^^^^^^^^^^^^^^
   |
   = note: #[warn(deprecated)] on by default

warning: use of deprecated item: gcc::Config has been renamed to gcc::Build
  --> tcod_sys\build.rs:18:38
   |
18 | fn build_libtcod_objects(mut config: gcc::Config, sources: &[&str]) {
   |                                      ^^^^^^^^^^^
   |
   = note: #[warn(deprecated)] on by default

warning: use of deprecated item: gcc::Config has been renamed to gcc::Build
  --> tcod_sys\build.rs:30:27
   |
30 | fn compile_config(config: gcc::Config) {
   |                           ^^^^^^^^^^^
   |
   = note: #[warn(deprecated)] on by default

warning: use of deprecated item: gcc::Config has been renamed to gcc::Build
   --> tcod_sys\build.rs:119:30
    |
119 |             let mut config = gcc::Config::new();
    |                              ^^^^^^^^^^^^^^^^
    |
    = note: #[warn(deprecated)] on by default

warning: use of deprecated item: gcc::Config has been renamed to gcc::Build
   --> tcod_sys\build.rs:126:26
    |
126 |         let mut config = gcc::Config::new();
    |                          ^^^^^^^^^^^^^^^^
    |
    = note: #[warn(deprecated)] on by default

warning: use of deprecated item: gcc::Config has been renamed to gcc::Build
   --> tcod_sys\build.rs:154:30
    |
154 |             let mut config = gcc::Config::new();
    |                              ^^^^^^^^^^^^^^^^
    |
    = note: #[warn(deprecated)] on by default

warning: use of deprecated item: gcc::Config has been renamed to gcc::Build
   --> tcod_sys\build.rs:161:26
    |
161 |         let mut config = gcc::Config::new();
    |                          ^^^^^^^^^^^^^^^^
    |
    = note: #[warn(deprecated)] on by default

warning: use of deprecated item: gcc::Config has been renamed to gcc::Build
   --> tcod_sys\build.rs:196:30
    |
196 |             let mut config = gcc::Config::new();
    |                              ^^^^^^^^^^^^^^^^
    |
    = note: #[warn(deprecated)] on by default

warning: use of deprecated item: gcc::Config has been renamed to gcc::Build
   --> tcod_sys\build.rs:205:26
    |
205 |         let mut config = gcc::Config::new();
    |                          ^^^^^^^^^^^^^^^^
    |
    = note: #[warn(deprecated)] on by default

warning: use of deprecated item: gcc::Config has been renamed to gcc::Build
   --> tcod_sys\build.rs:239:26
    |
239 |         let mut config = gcc::Config::new();
    |                          ^^^^^^^^^^^^^^^^
    |
    = note: #[warn(deprecated)] on by default

**Comment by huhlig** [comment]
Created [pull request](https://github.com/tomassedovic/tcod-rs/pull/252) with changes to match new API.

**Comment by linkmauve** [comment]
This issue should be fixed, the above PR has been merged on Sep 4.

**Comment by tomassedovic** [comment]
Thanks for the reminder. This should be fixed, please reopen the issue if it isn't.
