### ISSUE TITLE
Incorrect Key Match Arm

### ISSUE THREAD

**Issue by brandonedens** [tomassedovic/tcod-rs#258]
It appears that its possible for the match statement when using stable 1.26.2 to incorrectly match the wrong key code as shown here:

```
extern crate tcod;

use tcod::input::{self, Key};
// Uncommented the following line fixes the problem.
//use tcod::input::KeyCode::*;

fn main() {

    let mut key = Default::default();
    println!("key is: {:?}", key);

    match key {
        Key { code: Up, .. } => {
            println!("Up");
        },
        Key { code: Escape, .. } => {
            println!("Escape");
        },
        Key { code: NoKey, .. } => {
            println!("NoKey");
        },
        _ => {
            println!("Got other key");
        }
    }
}
```

Which results in the output:
```
▶ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/tcod-broken`
key is: Key { code: NoKey, printable: '\u{0}', pressed: false, left_alt: false, left_ctrl: false, right_alt: false, right_ctrl: false, shift: false, alt: false, ctrl: false }
Up
```

But apparently works if member code is specified via either:
```
KeyCode::Up
```
or
```
use tcod::input::KeyCode::*;
```
is brought into scope.

Any ideas?

**Comment by tomassedovic** [comment]
This is how Rust match statements work (and have always done as long as I remember). Observe this (which has nothing to do with tcod):

http://play.rust-lang.org/?gist=71af4c91eed131206197079c4c8b69f6&version=stable&mode=debug

Basically, if the enum variant you want to match on is not in scope, Rust treats it as a name to bind your value into. I definitely think this behaviour can be confusing.

For that reason however, Rust prints ton of warnings about this.

I'm surprised that your cargo run does not show any. As you can see in the playground link above, Rust should show a warning about this exact situation and a suggestion on how to fix it as well as point out that the other match arms are unreachable and that the variable name is `CamelCase` and not `snake_case`.

Is there any chance you've disabled warnings or were not paying attention to them?

I don't think that's something the tcod library has a control over.

**Comment by brandonedens** [comment]
It matched Up rather than NoKey when the default is NoKey; without errors. Do you see?

I'll reach out to the compiler internals team.

**Comment by brandonedens** [comment]
To be clear, I expect:
If Up, Escape, and NoKey were not imported I'd expect a compile failure.

I expect the match to not take an arm that is different from the default() which sets Key struct field code to something other than KeyCode::NoKey.

Finally I should note that it'll skip arms when I include specification of bool struct fields like pressed with true rather than the default() of false.

**Comment by tomassedovic** [comment]
Right, so unfortunately Rust's match doesn't work the way you'd like it to :-(. I'm pretty sure this is by design.

Your first match arm says `Key { code: Up, .. }`. Since there is no `Up` type in scope (unless you do `tcod::input::KeyCode::*` or specify `KeyCode::Up` as you've discovered), Rust interprets this like this:

"match any `Key` struct and storing its `code` member value into a variable called `Up`".

Here's the closest you can get to a compile-time failure. You put this at the top of your program: `#![deny(unreachable_patterns)]`. Then all warnings of this type will be turned into errors:

http://play.rust-lang.org/?gist=9869d5497141581084c3161f1ca7a9b1&version=stable&mode=debug

You can turn warnings into errors that way individually, or you can error out on any warning like so: `#![deny(warnings)]`.

**Comment by brandonedens** [comment]
I understand now.

I specified that I wanted to create a new symbol known as Up and bind the matching arm's Key code field into it so that I could utilize it in the arm's => { println!("Up is: {:?}", Up); },
but with the bool which is already in scope it was able to accept / reject a match by the fact that I stipulated pressed: false or pressed: true.

Yikes...
Thanks for the clarification.

**Comment by tomassedovic** [comment]
Yeah, exactly. No worries.

I do find that this behaviour trips people up -- especially when they're newer to the language. I've been a little confused by this myself when I got started.
