### ISSUE TITLE
Bsp::split_recursive consumes the rng

### ISSUE THREAD

**Issue by L3nn0x** [tomassedovic/tcod-rs#260]
`Bsp::split_recursive()` takes an `Option<Rng>` which consumes the rng. It would be better if the Bsp didn't consume the rng as it could be used after splitting (for example to generate monsters).

**Comment by L3nn0x** [comment]
I'll try to take a look

**Comment by L3nn0x** [comment]
I had a look at the libtcod code and the pointer isn't stored anywhere.
I did find this code however: `if (! randomizer ) randomizer=TCODRandom::getInstance();`, which means that we could send a `nullptr` if the option is `None`. I'll make a PR shortly.

**Comment by tomassedovic** [comment]
The PR #261 has been merged (sheesh, what took the maintainers so long amirite?) so I'm closing this issue. Thanks again!
