### ISSUE TITLE
Building on Mac OS X required SDL2

### ISSUE THREAD

**Issue by bshea5** [tomassedovic/tcod-rs#277]
Instructions specify installing sdl with homebrew, but I had to install sdl2 in order for it to build. Here is the error from the build process. It was remedied once I installed sdl2.

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"sdl2\"` did not exit successfully: exit code: 1\n--- stderr\nPackage sdl2 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `sdl2.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'sdl2\' found\n"', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.`

**Comment by tomassedovic** [comment]
Ah we've missed a spot, thanks!

So should the instructions here be `brew install pkg-config sdl2`?

https://github.com/tomassedovic/tcod-rs#building-on-mac-os-x

**Comment by bshea5** [comment]
That is what worked for me, so I think so.
