### ISSUE TITLE
WeightedChoice depreciated - Uses old rand::distributions module

### ISSUE THREAD

**Issue by ToferC** [tomassedovic/tcod-rs#305]
First - amazing work and huge thanks for the tutorial and this module. I know you haven't had time to keep it updated, but wanted to add the issue for other users.

I'm fairly new to Rust and love the flow of the tutorial and am finding it really useful to get familiar with basic gamedev and loops as well.

As for the issue, it seems like `WeightedChoice` and `Weighted` in https://tomassedovic.github.io/roguelike-tutorial/part-12-monster-item-progression.html has been depreciated in favour of `rand::distributions::WeightedIndex`

The pull request and discussion seems to have gone on here: https://github.com/rust-random/rand/pull/518

A working update for the first part using WeightedIndex:

```rust
let monster_chances = [
                ("orc", 80),
                ("troll", 20),
            ];

let dist = WeightedIndex::new(monster_chances.iter().map(
    |item| item.1)).unwrap();    
                
let mut rng = rand::thread_rng();

let choice = monster_chances[dist.sample(&mut rng)].0;

let mut monster = match choice {
    "orc" => Object {
        // return object
        }
```

Cheers!

**Comment by ThibaultLemaire** [comment]
Yes I have run into the same issue while doing the tutorial last month, but I'm afraid you're on the wrong project.

The project hosting the code for the tutorial already has an issue open: https://github.com/tomassedovic/roguelike-tutorial/issues/40

**Comment by ToferC** [comment]
Sorry about that. Closing.
