### ISSUE TITLE
Cant build project  on linux

### ISSUE THREAD

**Issue by Sangsua** [tomassedovic/tcod-rs#312]
I just added tcod to my Cargo.toml file and build it... it doesn't seem to work
![Bildschirmfoto von 2020-07-15 02-27-01](https://user-images.githubusercontent.com/32667781/87489263-e4fabc00-c642-11ea-8d64-eb40eee0f010.png)

**Comment by tomassedovic** [comment]
Hey @Sangsua! I'm sorry for the trouble!

Can you please show us the rest of the log (lines after 25)?

Also, tcod-sys requires some libraries to be installed:

https://github.com/tomassedovic/tcod-rs#building-on-linux

Please try installing them (`sudo apt-get install gcc g++ make libsdl2-dev`), that should help if you didn't do it already.

What is your Linux distro? The instructions are for Ubuntu, the actual command and package names would be different on other distros.

**Comment by Sangsua** [comment]
I'm using Manjaro, it doesn't seem to have libsdl2-dev :( . Here is the rest of the log.
![Bildschirmfoto von 2020-07-15 10-13-08](https://user-images.githubusercontent.com/32667781/87521001-0c25ad80-c684-11ea-9557-56ba3bc9c924.png)

**Comment by tomassedovic** [comment]
Thanks! So the tcod-sys build script cannot find the SDL2 package. Looks like Arch and Manjaro bundle the header files with the libraries.

Try installing the `sdl2` package.

**Comment by Sangsua** [comment]
pkg-config and sdl2 were the culprits. :) thanks for the help
