### ISSUE TITLE
Build error when adding tcod="0.15" to [dependencies]

### ISSUE THREAD

**Issue by LBreede** [tomassedovic/tcod-rs#318]
Hitting a roadblock very early in Tomas Sedovic' Roguelike Tutorial. All I've done is add:
`tcod = "0.15"` to the dependencies and used `brew` to install `pkg-config` and `sdl2`.
I'm on macOS Ventura 13.4.1.
Let me know if there's any more useful info I can provide. This is my first issue I've opened.

The build error:
```
cargo build --release
    Updating crates.io index
   Compiling tcod-sys v5.0.1
The following warnings were emitted during compilation:

warning: libtcod/src/zlib/gzlib.c:256:24: error: call to undeclared function 'lseek'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

...
```

**Comment by tomassedovic** [comment]
Hi! I'm sorry but this project hasn't been maintained for a while.

Please check the readme for much more viable alternatives:

https://github.com/tomassedovic/tcod-rs#alternatives

**Comment by LBreede** [comment]
@tomassedovic I noticed that the second I pressed submit, sorry about that and thanks for replying :)
