### ISSUE TITLE
Crashes with precompiled libtcod-migw on Windows

### ISSUE THREAD

**Issue by tomassedovic** [tomassedovic/tcod-rs#54]
This is on a 32bit version of Windows 7 with MinGW and MSYS (dependencies for building libtcod) installed.

When using tcod-rs with the libtcod compiled as part of tcod-sys, none of the examples crash. But when I download the precompiled `libtcod-1.5.2-mingw32.tar.gz` library from:

http://roguecentral.org/doryen/libtcod/download/

and run e.g. the `minimal` example, I get a panic unwrapping the Option here:

https://github.com/tomassedovic/tcod-rs/blob/100ec46048d56371c49371f9c33319ef09edfc85/src/lib.rs#L205

The `tcod_key.vk` values appear to be 256 or greater (hence the failure although this shouldn't ever happen) and when I try to inspect it, I end up with weird crashes (segfaults?) which seem to depend on things such as having a `println!(tcod_key.vk)` line in there or not.

I'll try to investigate this further but it seems like some sort of memory layout issue or something like that.

**Comment by L3nn0x** [comment]
It's most definitely a change in the ABI, see : http://roguecentral.org/doryen/2013/03/the-wonderful-world-of-c/ for more information. (I know it's an old issue, but there's nothing you can do except provide newer pre-compiled binaries or use an older compiler, so I think it's just better to close it and warn the users instead.)

**Comment by tomassedovic** [comment]
Thanks @L3nn0x. Yeah, I'll close this.
