### ISSUE TITLE
Weird colours with some libtcod versions on Windows

### ISSUE THREAD

**Issue by tomassedovic** [tomassedovic/tcod-rs#55]
Running `cargo run --example colors` on my 32bit Windows 7 VM produces incorrect values for the predefined colours:

This is what the window should look like:

![tcod-colors-good](https://cloud.githubusercontent.com/assets/104339/5544326/b0fb1410-8b04-11e4-89ba-4dd9232f3ead.png)

(and it does look like that on Linux and with precompiled libtcod-1.5.2-mingw32.tar.gz from http://roguecentral.org/doryen/libtcod/download/)

This is what it looks like on precompiled libtcod-1.5.1-mingw32.zip and also with the libtcod 1.5.x checkout bundled with tcod-sys:

![tcod-colors-bad](https://cloud.githubusercontent.com/assets/104339/5544343/074a84d6-8b05-11e4-9f5e-89faa6dabb8f.png)

Colours specified by their values (e.g. `tcod::Color{r: 12, g: 14, b: 128}`) display correctly, but the ones exported by name (e.g. `tcod::colors::darkest_green`) appear to return wrong values.

**Comment by dkaste** [comment]
The same example on my 64-bit Windows 7 machine produces the following results:

![tcod-test](https://cloud.githubusercontent.com/assets/9663536/6100392/d8a679b2-afdc-11e4-8e92-677615cc6dcb.png)

Note that I'm using a 32-bit Rust compiler and the bundled libtcod.

I might look into this bug further, but I have a feeling it'll be hard to pinpoint.

**Comment by tomassedovic** [comment]
Interesting. I really want to fix this but I have no idea why and since you can specify the colours directly, it's not such a high priority.

Then again, it is a problem and I worry what else may be broken.

If you do happen to figure it out, I'll be very grateful.

**Comment by Gustorn** [comment]
I cannot reproduce this bug with the setup described by @dkaste in #141. Is this still happening to other people?

**Comment by dkaste** [comment]
Strangely, I'm no longer having this issue. If @tomassedovic can confirm, I think it might be fixed.

I _really_ hope that upper-casing the static colors isn't what fixed it...

**Comment by tomassedovic** [comment]
This should be "fixed" now. Previously, we were just "re-exporting" the static colour values defined in libtcod. That used to return different values than it was supposed to. And I'm not sure if that's still the case or not.

However, in the meantime, we've switched to just defining the colour values in src/lib.rs for an unrelated reason, so this can be closed.
