### ISSUE TITLE
Another error while compiling

### ISSUE THREAD

**Issue by GBGamer** [tomassedovic/tcod-rs#60]
lib.rs:9:44: 9:45 error: expected one of `(`, `+`, `::`, `;`, or `]`, found `,`
lib.rs:9 pub type __builtin_va_list = [__va_list_tag, ..1u];

**Comment by DrKwint** [comment]
This issue seems to be a consequence of updating one's rustc to nightly.

I have the same issue with rustc 0.13.0-nightly (c6c786671 2015-01-04 00:50:59 +0000)

**Comment by jgilchrist** [comment]
I've issued a pull request to fix the errors (#64)

**Comment by tomassedovic** [comment]
#61 is merged and should fix the issues. Thanks everyone!
