### ISSUE TITLE
Auto-build documentation

### ISSUE THREAD

**Issue by jgilchrist** [tomassedovic/tcod-rs#64]
My roguelike repository is set up so that every time a commit is pushed to master, Travis builds the docs and puts them on the Github Page for the repository.

Would you like me to set this up for tcod-rs? People would be able to access the latest docs at `tomassedovic.github.io/tcod-rs`.

**Comment by tomassedovic** [comment]
Is this a secret ploy to make me write documentation? It's pretty much nonexistent atm, but yeah we need that. The Rusty wrapper is different enough to warrant its own docs.

If you could set it up, that would be absolutely fantastic.

**Comment by jgilchrist** [comment]
I've actually got a branch which I was going to start writing documentation on, but even without doc-strings the documentation rustdoc generates is quite useful. If I've got time tonight I'll set it up then, if not I'll do it tomorrow.

**Comment by tomassedovic** [comment]
Awesome, thanks :-).

**Comment by jgilchrist** [comment]
Well, it's working for my fork, so I should in theory just be able to commit the change and have it work automatically for this repo too.

**Comment by jgilchrist** [comment]
It's working! http://tomassedovic.github.io/tcod-rs/

**Comment by tomassedovic** [comment]
Yep! Now there's no excuse for not writing proper docstrings.
