### ISSUE TITLE
Needs to be updated to rust-alpha

### ISSUE THREAD

**Issue by GBGamer** [tomassedovic/tcod-rs#69]
```
src/lib.rs:1:12: 1:28 warning: feature has been added to Rust, directive not necessary
src/lib.rs:1 #![feature(associated_types, globs, unboxed_closures)]
                        ^~~~~~~~~~~~~~~~
src/lib.rs:1:30: 1:35 warning: feature has been added to Rust, directive not necessary
src/lib.rs:1 #![feature(associated_types, globs, unboxed_closures)]
                                          ^~~~~
src/lib.rs:1:12: 1:28 warning: feature has been added to Rust, directive not necessary
src/lib.rs:1 #![feature(associated_types, globs, unboxed_closures)]
                        ^~~~~~~~~~~~~~~~
src/lib.rs:1:30: 1:35 warning: feature has been added to Rust, directive not necessary
src/lib.rs:1 #![feature(associated_types, globs, unboxed_closures)]
                                          ^~~~~
src/lib.rs:12:5: 12:23 error: unresolved import `std::c_str::ToCStr`. Could not find `c_str` in `std`
src/lib.rs:12 use std::c_str::ToCStr;
```

**Comment by jgilchrist** [comment]
@tomassedovic I don't know how you'd feel about this, but is there any chance that you could add me to the managers of the tcod crate on crates.io? That way I can publish new versions of the crate when updating for new versions of Rust.

**Comment by tomassedovic** [comment]
@jgilchrist would love to! Do you happen know how to do that? Quick glance at the UI didn't help. I'll try to find out.

**Comment by tomassedovic** [comment]
ah, here we go: http://doc.crates.io/crates-io.html#cargo-owner

@jgilchrist thanks for all your help in the last few days. You an owner of `tcod` and `tcod-sys` crates now :-)

**Comment by jgilchrist** [comment]
Brilliant, just to check I know what's going on I'll bump the version and try and release a new version to crates.io which will run on the latest rust. No worries, and thanks!

**Comment by jgilchrist** [comment]
It worked, brilliant! 0.3.2 is out.

**Comment by tomassedovic** [comment]
Sweet!
