### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by jgilchrist** [tomassedovic/tcod-rs#75]
I'm going to go through the history and add tags for each time a new version has been released. This makes each release show up on Github (https://github.com/tomassedovic/tcod-rs/releases) and that page is a good place to write release notes.

**Comment by tomassedovic** [comment]
Great idea! With crates.io I've completely forgotten about tags and how github turns them into downloadable releases.

**Comment by jgilchrist** [comment]
Any idea which commit it was where you made the initial release to crates.io? I can find most of them because we bumped the version but not that one.

**Comment by tomassedovic** [comment]
I'm pretty sure it's commit c908304e4156a62ac083abb5dde6d0b15b44930e.

**Comment by jgilchrist** [comment]
Done, the tags are pushed, I'll see about adding some short release notes to the releases in a bit.

**Comment by tomassedovic** [comment]
Awesome, thanks!

**Comment by jgilchrist** [comment]
Okay, I've gone through and written some minimal release notes going back to `0.3.1`.

**Comment by tomassedovic** [comment]
\o/
